
import type { MLBStadium, NFLStadium, USState, NationalPark } from '@/types';

export const mlbBallparks: MLBStadium[] = [
  { id: "ARI", name: "Chase Field", team: "Arizona Diamondbacks", city: "Phoenix", state: "AZ" },
  { id: "ATL", name: "Truist Park", team: "Atlanta Braves", city: "Cumberland", state: "GA" },
  { id: "BAL", name: "Oriole Park at Camden Yards", team: "Baltimore Orioles", city: "Baltimore", state: "MD" },
  { id: "BOS", name: "Fenway Park", team: "Boston Red Sox", city: "Boston", state: "MA" },
  { id: "CHC", name: "Wrigley Field", team: "Chicago Cubs", city: "Chicago", state: "IL" },
  { id: "CHW", name: "Guaranteed Rate Field", team: "Chicago White Sox", city: "Chicago", state: "IL" },
  { id: "CIN", name: "Great American Ball Park", team: "Cincinnati Reds", city: "Cincinnati", state: "OH" },
  { id: "CLE", name: "Progressive Field", team: "Cleveland Guardians", city: "Cleveland", state: "OH" },
  { id: "COL", name: "Coors Field", team: "Colorado Rockies", city: "Denver", state: "CO" },
  { id: "DET", name: "Comerica Park", team: "Detroit Tigers", city: "Detroit", state: "MI" },
  { id: "HOU", name: "Minute Maid Park", team: "Houston Astros", city: "Houston", state: "TX" },
  { id: "KCR", name: "Kauffman Stadium", team: "Kansas City Royals", city: "Kansas City", state: "MO" },
  { id: "LAA", name: "Angel Stadium", team: "Los Angeles Angels", city: "Anaheim", state: "CA" },
  { id: "LAD", name: "Dodger Stadium", team: "Los Angeles Dodgers", city: "Los Angeles", state: "CA" },
  { id: "MIA", name: "LoanDepot Park", team: "Miami Marlins", city: "Miami", state: "FL" },
  { id: "MIL", name: "American Family Field", team: "Milwaukee Brewers", city: "Milwaukee", state: "WI" },
  { id: "MIN", name: "Target Field", team: "Minnesota Twins", city: "Minneapolis", state: "MN" },
  { id: "NYM", name: "Citi Field", team: "New York Mets", city: "Queens", state: "NY" },
  { id: "NYY", name: "Yankee Stadium", team: "New York Yankees", city: "Bronx", state: "NY" },
  { id: "OAK", name: "Oakland Coliseum", team: "Oakland Athletics", city: "Oakland", state: "CA" },
  { id: "PHI", name: "Citizens Bank Park", team: "Philadelphia Phillies", city: "Philadelphia", state: "PA" },
  { id: "PIT", name: "PNC Park", team: "Pittsburgh Pirates", city: "Pittsburgh", state: "PA" },
  { id: "SDP", name: "Petco Park", team: "San Diego Padres", city: "San Diego", state: "CA" },
  { id: "SEA", name: "T-Mobile Park", team: "Seattle Mariners", city: "Seattle", state: "WA" },
  { id: "SFG", name: "Oracle Park", team: "San Francisco Giants", city: "San Francisco", state: "CA" },
  { id: "STL", name: "Busch Stadium", team: "St. Louis Cardinals", city: "St. Louis", state: "MO" },
  { id: "TBR", name: "Tropicana Field", team: "Tampa Bay Rays", city: "St. Petersburg", state: "FL" },
  { id: "TEX", name: "Globe Life Field", team: "Texas Rangers", city: "Arlington", state: "TX" },
  { id: "TOR", name: "Rogers Centre", team: "Toronto Blue Jays", city: "Toronto", state: "ON" },
  { id: "WSN", name: "Nationals Park", team: "Washington Nationals", city: "Washington", state: "DC" }
];

export const nflStadiums: NFLStadium[] = [
  { id: "arizona-cardinals", name: "State Farm Stadium", team: "Arizona Cardinals", city: "Glendale", state: "Arizona" },
  { id: "atlanta-falcons", name: "Mercedes-Benz Stadium", team: "Atlanta Falcons", city: "Atlanta", state: "Georgia" },
  { id: "baltimore-ravens", name: "M&T Bank Stadium", team: "Baltimore Ravens", city: "Baltimore", state: "Maryland" },
  { id: "buffalo-bills", name: "Highmark Stadium", team: "Buffalo Bills", city: "Orchard Park", state: "New York" },
  { id: "carolina-panthers", name: "Bank of America Stadium", team: "Carolina Panthers", city: "Charlotte", state: "North Carolina" },
  { id: "chicago-bears", name: "Soldier Field", team: "Chicago Bears", city: "Chicago", state: "Illinois" },
  { id: "cincinnati-bengals", name: "Paycor Stadium", team: "Cincinnati Bengals", city: "Cincinnati", state: "Ohio" },
  { id: "cleveland-browns", name: "Cleveland Browns Stadium", team: "Cleveland Browns", city: "Cleveland", state: "Ohio" },
  { id: "dallas-cowboys", name: "AT&T Stadium", team: "Dallas Cowboys", city: "Arlington", state: "Texas" },
  { id: "denver-broncos", name: "Empower Field at Mile High", team: "Denver Broncos", city: "Denver", state: "Colorado" },
  { id: "detroit-lions", name: "Ford Field", team: "Detroit Lions", city: "Detroit", state: "Michigan" },
  { id: "green-bay-packers", name: "Lambeau Field", team: "Green Bay Packers", city: "Green Bay", state: "Wisconsin" },
  { id: "houston-texans", name: "NRG Stadium", team: "Houston Texans", city: "Houston", state: "Texas" },
  { id: "indianapolis-colts", name: "Lucas Oil Stadium", team: "Indianapolis Colts", city: "Indianapolis", state: "Indiana" },
  { id: "jacksonville-jaguars", name: "EverBank Stadium", team: "Jacksonville Jaguars", city: "Jacksonville", state: "Florida" },
  { id: "kansas-city-chiefs", name: "GEHA Field at Arrowhead Stadium", team: "Kansas City Chiefs", city: "Kansas City", state: "Missouri" },
  { id: "las-vegas-raiders", name: "Allegiant Stadium", team: "Las Vegas Raiders", city: "Paradise", state: "Nevada" },
  { id: "los-angeles-chargers", name: "SoFi Stadium", team: "Los Angeles Chargers", city: "Inglewood", state: "California" },
  { id: "los-angeles-rams", name: "SoFi Stadium", team: "Los Angeles Rams", city: "Inglewood", state: "California" },
  { id: "miami-dolphins", name: "Hard Rock Stadium", team: "Miami Dolphins", city: "Miami Gardens", state: "Florida" },
  { id: "minnesota-vikings", name: "U.S. Bank Stadium", team: "Minnesota Vikings", city: "Minneapolis", state: "Minnesota" },
  { id: "new-england-patriots", name: "Gillette Stadium", team: "New England Patriots", city: "Foxborough", state: "Massachusetts" },
  { id: "new-orleans-saints", name: "Caesars Superdome", team: "New Orleans Saints", city: "New Orleans", state: "Louisiana" },
  { id: "new-york-giants", name: "MetLife Stadium", team: "New York Giants", city: "East Rutherford", state: "New Jersey" },
  { id: "new-york-jets", name: "MetLife Stadium", team: "New York Jets", city: "East Rutherford", state: "New Jersey" },
  { id: "philadelphia-eagles", name: "Lincoln Financial Field", team: "Philadelphia Eagles", city: "Philadelphia", state: "Pennsylvania" },
  { id: "pittsburgh-steelers", name: "Acrisure Stadium", team: "Pittsburgh Steelers", city: "Pittsburgh", state: "Pennsylvania" },
  { id: "san-francisco-49ers", name: "Levi's Stadium", team: "San Francisco 49ers", city: "Santa Clara", state: "California" },
  { id: "seattle-seahawks", name: "Lumen Field", team: "Seattle Seahawks", city: "Seattle", state: "Washington" },
  { id: "tampa-bay-buccaneers", name: "Raymond James Stadium", team: "Tampa Bay Buccaneers", city: "Tampa", state: "Florida" },
  { id: "tennessee-titans", name: "Nissan Stadium", team: "Tennessee Titans", city: "Nashville", state: "Tennessee" },
  { id: "washington-commanders", name: "Northwest Stadium", team: "Washington Commanders", city: "Landover", state: "Maryland" }
];
