import type { MLBStadium, NFLStadium, USState, NationalPark } from '@/types';

export const usStates: USState[] = [
  { id: "01", name: "Alabama" }, { id: "02", name: "Alaska" }, { id: "04", name: "Arizona" },
  { id: "05", name: "Arkansas" }, { id: "06", name: "California" }, { id: "08", name: "Colorado" },
  { id: "09", name: "Connecticut" }, { id: "10", name: "Delaware" }, { id: "12", name: "Florida" },
  { id: "13", name: "Georgia" }, { id: "15", name: "Hawaii" }, { id: "16", name: "Idaho" },
  { id: "17", name: "Illinois" }, { id: "18", name: "Indiana" }, { id: "19", name: "Iowa" },
  { id: "20", name: "Kansas" }, { id: "21", name: "Kentucky" }, { id: "22", name: "Louisiana" },
  { id: "23", name: "Maine" }, { id: "24", name: "Maryland" }, { id: "25", name: "Massachusetts" },
  { id: "26", name: "Michigan" }, { id: "27", name: "Minnesota" }, { id: "28", name: "Mississippi" },
  { id: "29", name: "Missouri" }, { id: "30", name: "Montana" }, { id: "31", name: "Nebraska" },
  { id: "32", name: "Nevada" }, { id: "33", name: "New Hampshire" }, { id: "34", name: "New Jersey" },
  { id: "35", name: "New Mexico" }, { id: "36", name: "New York" }, { id: "37", name: "North Carolina" },
  { id: "38", name: "North Dakota" }, { id: "39", name: "Ohio" }, { id: "40", name: "Oklahoma" },
  { id: "41", name: "Oregon" }, { id: "42", name: "Pennsylvania" }, { id: "44", name: "Rhode Island" },
  { id: "45", name: "South Carolina" }, { id: "46", name: "South Dakota" }, { id: "47", name: "Tennessee" },
  { id: "48", name: "Texas" }, { id: "49", name: "Utah" }, { id: "50", name: "Vermont" },
  { id: "51", name: "Virginia" }, { id: "53", name: "Washington" }, { id: "54", name: "West Virginia" },
  { id: "55", name: "Wisconsin" }, { id: "56", name: "Wyoming" }
];

export const nationalParks: NationalPark[] = [
    { id: "acad", name: "Acadia", state: "ME" }, { id: "arch", name: "Arches", state: "UT" },
    { id: "badl", name: "Badlands", state: "SD" }, { id: "bibe", name: "Big Bend", state: "TX" },
    { id: "bisc", name: "Biscayne", state: "FL" }, { id: "blca", name: "Black Canyon of the Gunnison", state: "CO" },
    { id: "brca", name: "Bryce Canyon", state: "UT" }, { id: "cany", name: "Canyonlands", state: "UT" },
    { id: "care", name: "Capitol Reef", state: "UT" }, { id: "cave", name: "Carlsbad Caverns", state: "NM" },
    { id: "chis", name: "Channel Islands", state: "CA" }, { id: "cong", name: "Congaree", state: "SC" },
    { id: "crla", name: "Crater Lake", state: "OR" }, { id: "cuva", name: "Cuyahoga Valley", state: "OH" },
    { id: "dena", name: "Denali", state: "AK" }, { id: "drto", name: "Dry Tortugas", state: "FL" },
    { id: "ever", name: "Everglades", state: "FL" }, { id: "gaar", name: "Gates of the Arctic", state: "AK" },
    { id: "grca", name: "Grand Canyon", state: "AZ" }, { id: "grte", name: "Grand Teton", state: "WY" },
    { id: "grba", name: "Great Basin", state: "NV" }, { id: "grsa", name: "Great Sand Dunes", state: "CO" },
    { id: "grsm", name: "Great Smoky Mountains", state: "NC,TN" }, { id: "gumo", name: "Guadalupe Mountains", state: "TX" },
    { id: "hale", name: "Haleakalā", state: "HI" }, { id: "havo", name: "Hawai'i Volcanoes", state: "HI" },
    { id: "hosp", name: "Hot Springs", state: "AR" }, { id: "isro", name: "Isle Royale", state: "MI" },
    { id: "jotr", name: "Joshua Tree", state: "CA" }, { id: "katm", name: "Katmai", state: "AK" },
    { id: "kefj", name: "Kenai Fjords", state: "AK" }, { id: "kova", name: "Kobuk Valley", state: "AK" },
    { id: "lacl", name: "Lake Clark", state: "AK" }, { id: "lavo", name: "Lassen Volcanic", state: "CA" },
    { id: "maca", name: "Mammoth Cave", state: "KY" }, { id: "meve", name: "Mesa Verde", state: "CO" },
    { id: "mora", name: "Mount Rainier", state: "WA" }, { id: "noca", name: "North Cascades", state: "WA" },
    { id: "olym", name: "Olympic", state: "WA" }, { id: "pefo", name: "Petrified Forest", state: "AZ" },
    { id: "pinn", name: "Pinnacles", state: "CA" }, { id: "redw", name: "Redwood", state: "CA" },
    { id: "romo", name: "Rocky Mountain", state: "CO" }, { id: "sagu", name: "Saguaro", state: "AZ" },
    { id: "sequ", name: "Sequoia &amp; Kings Canyon", state: "CA" }, { id: "shen", name: "Shenandoah", state: "VA" },
    { id: "thro", name: "Theodore Roosevelt", state: "ND" }, { id: "viis", name: "Virgin Islands", state: "VI" },
    { id: "voya", name: "Voyageurs", state: "MN" }, { id: "wica", name: "Wind Cave", state: "SD" },
    { id: "wrst", name: "Wrangell-St. Elias", state: "AK" }, { id: "yell", name: "Yellowstone", state: "WY,MT,ID" },
    { id: "yose", name: "Yosemite", state: "CA" }, { id: "zion", name: "Zion", state: "UT" },
    { id: "npsa", name: "National Park of American Samoa", state: "AS" },
    { id: "neri", name: "New River Gorge", state: "WV" },
    { id: "whit", name: "White Sands", state: "NM" },
    { id: "indi", name: "Indiana Dunes", state: "IN" },
    { id: "jeff", name: "Gateway Arch", state: "MO" }
];

export const mlbBallparks: MLBStadium[] = [
  { id: "ARI", name: "Chase Field", team: "Arizona Diamondbacks", city: "Phoenix", state: "AZ" },
  { id: "ATL", name: "Truist Park", team: "Atlanta Braves", city: "Cumberland", state: "GA" },
  { id: "BAL", name: "Oriole Park at Camden Yards", team: "Baltimore Orioles", city: "Baltimore", state: "MD" },
  { id: "BOS", name: "Fenway Park", team: "Boston Red Sox", city: "Boston", state: "MA" },
  { id: "CHC", name: "Wrigley Field", team: "Chicago Cubs", city: "Chicago", state: "IL" },
  { id: "CHW", name: "Guaranteed Rate Field", team: "Chicago White Sox", city: "Chicago", state: "IL" },
  { id: "CIN", name: "Great American Ball Park", team: "Cincinnati Reds", city: "Cincinnati", state: "OH" },
  { id: "CLE", name: "Progressive Field", team: "Cleveland Guardians", city: "Cleveland", state: "OH" },
  { id: "COL", name: "Coors Field", team: "Colorado Rockies", city: "Denver", state: "CO" },
  { id: "DET", name: "Comerica Park", team: "Detroit Tigers", city: "Detroit", state: "MI" },
  { id: "HOU", name: "Minute Maid Park", team: "Houston Astros", city: "Houston", state: "TX" },
  { id: "KCR", name: "Kauffman Stadium", team: "Kansas City Royals", city: "Kansas City", state: "MO" },
  { id: "LAA", name: "Angel Stadium", team: "Los Angeles Angels", city: "Anaheim", state: "CA" },
  { id: "LAD", name: "Dodger Stadium", team: "Los Angeles Dodgers", city: "Los Angeles", state: "CA" },
  { id: "MIA", name: "LoanDepot Park", team: "Miami Marlins", city: "Miami", state: "FL" },
  { id: "MIL", name: "American Family Field", team: "Milwaukee Brewers", city: "Milwaukee", state: "WI" },
  { id: "MIN", name: "Target Field", team: "Minnesota Twins", city: "Minneapolis", state: "MN" },
  { id: "NYM", name: "Citi Field", team: "New York Mets", city: "Queens", state: "NY" },
  { id: "NYY", name: "Yankee Stadium", team: "New York Yankees", city: "Bronx", state: "NY" },
  { id: "OAK", name: "Oakland Coliseum", team: "Oakland Athletics", city: "Oakland", state: "CA" },
  { id: "PHI", name: "Citizens Bank Park", team: "Philadelphia Phillies", city: "Philadelphia", state: "PA" },
  { id: "PIT", name: "PNC Park", team: "Pittsburgh Pirates", city: "Pittsburgh", state: "PA" },
  { id: "SDP", name: "Petco Park", team: "San Diego Padres", city: "San Diego", state: "CA" },
  { id: "SEA", name: "T-Mobile Park", team: "Seattle Mariners", city: "Seattle", state: "WA" },
  { id: "SFG", name: "Oracle Park", team: "San Francisco Giants", city: "San Francisco", state: "CA" },
  { id: "STL", name: "Busch Stadium", team: "St. Louis Cardinals", city: "St. Louis", state: "MO" },
  { id: "TBR", name: "Tropicana Field", team: "Tampa Bay Rays", city: "St. Petersburg", state: "FL" },
  { id: "TEX", name: "Globe Life Field", team: "Texas Rangers", city: "Arlington", state: "TX" },
  { id: "TOR", name: "Rogers Centre", team: "Toronto Blue Jays", city: "Toronto", state: "ON" },
  { id: "WSN", name: "Nationals Park", team: "Washington Nationals", city: "Washington", state: "DC" }
];

export const nflStadiums: NFLStadium[] = [
  { id: "arizona-cardinals", name: "State Farm Stadium", team: "Arizona Cardinals", city: "Glendale", state: "Arizona" },
  { id: "atlanta-falcons", name: "Mercedes-Benz Stadium", team: "Atlanta Falcons", city: "Atlanta", state: "Georgia" },
  { id: "baltimore-ravens", name: "M&amp;T Bank Stadium", team: "Baltimore Ravens", city: "Baltimore", state: "Maryland" },
  { id: "buffalo-bills", name: "Highmark Stadium", team: "Buffalo Bills", city: "Orchard Park", state: "New York" },
  { id: "carolina-panthers", name: "Bank of America Stadium", team: "Carolina Panthers", city: "Charlotte", state: "North Carolina" },
  { id: "chicago-bears", name: "Soldier Field", team: "Chicago Bears", city: "Chicago", state: "Illinois" },
  { id: "cincinnati-bengals", name: "Paycor Stadium", team: "Cincinnati Bengals", city: "Cincinnati", state: "Ohio" },
  { id: "cleveland-browns", name: "Cleveland Browns Stadium", team: "Cleveland Browns", city: "Cleveland", state: "Ohio" },
  { id: "dallas-cowboys", name: "AT&amp;T Stadium", team: "Dallas Cowboys", city: "Arlington", state: "Texas" },
  { id: "denver-broncos", name: "Empower Field at Mile High", team: "Denver Broncos", city: "Denver", state: "Colorado" },
  { id: "detroit-lions", name: "Ford Field", team: "Detroit Lions", city: "Detroit", state: "Michigan" },
  { id: "green-bay-packers", name: "Lambeau Field", team: "Green Bay Packers", city: "Green Bay", state: "Wisconsin" },
  { id: "houston-texans", name: "NRG Stadium", team: "Houston Texans", city: "Houston", state: "Texas" },
  { id: "indianapolis-colts", name: "Lucas Oil Stadium", team: "Indianapolis Colts", city: "Indianapolis", state: "Indiana" },
  { id: "jacksonville-jaguars", name: "EverBank Stadium", team: "Jacksonville Jaguars", city: "Jacksonville", state: "Florida" },
  { id: "kansas-city-chiefs", name: "GEHA Field at Arrowhead Stadium", team: "Kansas City Chiefs", city: "Kansas City", state: "Missouri" },
  { id: "las-vegas-raiders", name: "Allegiant Stadium", team: "Las Vegas Raiders", city: "Paradise", state: "Nevada" },
  { id: "los-angeles-chargers", name: "SoFi Stadium", team: "Los Angeles Chargers", city: "Inglewood", state: "California" },
  { id: "los-angeles-rams", name: "SoFi Stadium", team: "Los Angeles Rams", city: "Inglewood", state: "California" },
  { id: "miami-dolphins", name: "Hard Rock Stadium", team: "Miami Dolphins", city: "Miami Gardens", state: "Florida" },
  { id: "minnesota-vikings", name: "U.S. Bank Stadium", team: "Minnesota Vikings", city: "Minneapolis", state: "Minnesota" },
  { id: "new-england-patriots", name: "Gillette Stadium", team: "New England Patriots", city: "Foxborough", state: "Massachusetts" },
  { id: "new-orleans-saints", name: "Caesars Superdome", team: "New Orleans Saints", city: "New Orleans", state: "Louisiana" },
  { id: "new-york-giants", name: "MetLife Stadium", team: "New York Giants", city: "East Rutherford", state: "New Jersey" },
  { id: "new-york-jets", name: "MetLife Stadium", team: "New York Jets", city: "East Rutherford", state: "New Jersey" },
  { id: "philadelphia-eagles", name: "Lincoln Financial Field", team: "Philadelphia Eagles", city: "Philadelphia", state: "Pennsylvania" },
  { id: "pittsburgh-steelers", name: "Acrisure Stadium", team: "Pittsburgh Steelers", city: "Pittsburgh", state: "Pennsylvania" },
  { id: "san-francisco-49ers", name: "Levi's Stadium", team: "San Francisco 49ers", city: "Santa Clara", state: "California" },
  { id: "seattle-seahawks", name: "Lumen Field", team: "Seattle Seahawks", city: "Seattle", state: "Washington" },
  { id: "tampa-bay-buccaneers", name: "Raymond James Stadium", team: "Tampa Bay Buccaneers", city: "Tampa", state: "Florida" },
  { id: "tennessee-titans", name: "Nissan Stadium", team: "Tennessee Titans", city: "Nashville", state: "Tennessee" },
  { id: "washington-commanders", name: "Northwest Stadium", team: "Washington Commanders", city: "Landover", state: "Maryland" }
];
